name: Run tests

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest            # same as the reused workflow
    steps:
      - uses: actions/checkout@v3

      - name: install direnv
        run: |
          sudo apt-get update
          sudo apt-get install -y direnv
          sudo apt install python3-colcon-common-extensions

      - name: install colcon-direnv
        run: |
          pip install --break-system-packages .

      - name: run tests
        run: |
          pytest -v test
